name: Deploy Node.js service to AWS Web App - dockerized-server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/setup-node@v4
        with:
          node-version: 22

       # 2. Autenticarse en AWS mediante OIDC
      # ...

      # 3. Login en ECR
      # ...

      # 4. Construir imagen
      # ...

      # 5. Push a ECR
      # ...

      # 6. Conectarse a EC2
      # ...

      # 7. Actualizar contenedor
      # ...